Q1: Questions on Basic NumPy Array

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])

[5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [2]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flat1 = array1.flatten()
flat2 = array1.ravel()
print(flat1)
print(flat2)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [3]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(arr1, arr2))

True


(d) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

In [5]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
val = np.bincount(x).argmax()
print(f"element = {val}, indeces = {np.where(x == val)}")

element = 1, indeces = (array([0, 5, 7, 8, 9], dtype=int64),)


ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [6]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
val = np.bincount(y).argmax()
print(f"element = {val}, indeces = {np.where(y== val)}")

element = 1, indeces = (array([0, 1, 2], dtype=int64),)


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all elements

In [6]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg.sum())

45


ii. Sum of all elements row-wise

In [7]:
print(gfg.sum(axis=1))

[[14]
 [16]
 [15]]


iii. Sum of all elements column-wise

In [8]:
print(gfg.sum(axis=0))

[[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

In [9]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(np.trace(n_array))

176


ii. Eigen values of matrix

In [10]:
print(np.linalg.eigvals(n_array))

[98.16835147 28.097044   49.73460452]


iii. Eigen vectors of matrix

In [11]:
eigvals, eigvecs = np.linalg.eig(n_array)
print(eigvecs)

[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


iv. Inverse of matrix

In [12]:
print(np.linalg.inv(n_array))

[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


v. Determinant of matrix

In [13]:
print(np.linalg.det(n_array))

137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]

In [7]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
print(np.dot(p1, q1))
if p1.shape == q1.shape:
    print(np.cov(p1.flatten(), q1.flatten()))
else:
    print("Shape mismatch")

[[16 19]
 [26 31]]
[[0.66666667 1.        ]
 [1.         1.66666667]]


ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

In [8]:
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
print(np.dot(p2, q2))
if p2.shape == q2.shape:
    print(np.cov(p2.flatten(), q2.flatten()))
else:
    print("Shape mismatch")

[[16 19  5]
 [26 31  8]
 [46 55 14]]
Shape mismatch


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print(np.inner(x, y))
print(np.outer(x, y))
# Need to understand
cartesian = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)
print(cartesian)


[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2: Based on NumPy Mathematics and Statistics

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value

In [18]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
print(np.abs(array))

[[1 2 3]
 [4 5 6]]


ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.

In [19]:
flat = array.flatten()
p25 = np.percentile(flat, 25)
p50 = np.percentile(flat, 50)
p75 = np.percentile(flat, 75)

p_col = np.percentile(array, [25, 50, 75], axis=0)
p_row = np.percentile(array, [25, 50, 75], axis=1)

print("25,50,75 of flat:", p25, p50, p75)
print("Percentiles (columns):\n", p_col)
print("Percentiles (rows):\n", p_row)

25,50,75 of flat: -3.5 -0.5 2.5
Percentiles (columns):
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles (rows):
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [20]:
mean_all = np.mean(flat)
median_all = np.median(flat)
std_all = np.std(flat)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print("Mean/Median/Std - flat:", mean_all, median_all, std_all)
print("Mean/Median/Std - col:", mean_col, median_col, std_col)
print("Mean/Median/Std - row:", mean_row, median_row, std_row)

Mean/Median/Std - flat: -0.5 -0.5 3.8622100754188224
Mean/Median/Std - col: [-1.5  1.5 -1.5] [-1.5  1.5 -1.5] [2.5 3.5 4.5]
Mean/Median/Std - row: [ 0.66666667 -1.66666667] [ 1. -4.] [2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [21]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements

In [22]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

# i
print(np.sort(array))
# ii
print(np.argsort(array))
# iii
print(np.partition(array, 3)[:4])
# iv
print(np.partition(array, -5)[-5:])


[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[16 10 16 52]
[ 16  52  62  54 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

i. Integer elements only
ii. Float elements only

In [23]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
# i. Integer elements
print(array[array == array.astype(int)])
# ii. Float elements
print(array[array != array.astype(int)])


[1. 2. 3. 2.]
[1.2 2.2]
